Repository btcven/locha-mesh-chat, pull requests merged in 2020-09, with the labels that each got.

#98 Feature/chat service
  App.js
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/DeviceInfo/Utils.java
  android/app/src/main/java/LocalNotification/LocalNotificationModule.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatService.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatServiceModule.java
  android/app/src/main/java/io/locha/p2p/runtime/EventReceivers.java
  android/app/src/main/rust/src/runtime.rs
Labels: Ready For Review

#97 Update locha-p2p crate
  android/app/src/main/rust/Cargo.lock
  android/app/src/main/rust/src/runtime.rs
Labels: work in progress

#102 the realmjs library was updated
  package.json
  yarn.lock
Labels: Ready For Review

#103 Send all locha-p2p RuntimeEvents to Java
  android/app/src/androidTest/java/io/locha/p2p/runtime/ChatServiceTest.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatService.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatServiceEvents.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatServiceModule.java
  android/app/src/main/java/io/locha/p2p/runtime/EventReceivers.java
  android/app/src/main/java/io/locha/p2p/runtime/EventsReceiver.java
  android/app/src/main/java/io/locha/p2p/util/LibraryLoader.java
  android/app/src/main/rust/src/runtime.rs
  android/app/src/main/rust/src/util/jni_cache.rs
Labels: Ready For Review, enhancement

#107 automatic reconnection
  src/components/Header.js
  src/views/home/Chat.js
Labels: Ready For Review

#106 Update locha-p2p crate to latest version
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/io/locha/p2p/LochaP2PPackage.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatService.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatServiceModule.java
  android/app/src/main/java/io/locha/p2p/runtime/Runtime.java
  android/app/src/main/java/io/locha/p2p/runtime/RuntimeEvents.java
  android/app/src/main/java/io/locha/p2p/service/ChatService.java
  android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
  android/app/src/main/java/io/locha/p2p/service/EventsDispatcher.java
  android/app/src/main/rust/Cargo.lock
  android/app/src/main/rust/Cargo.toml
  android/app/src/main/rust/src/runtime.rs
  android/app/src/main/rust/src/util/jni_cache.rs
  src/utils/chatService.js
Labels: Ready For Review, enhancement

#109 Update locha-p2p crate to latest version
  android/app/src/main/rust/Cargo.lock
  android/app/src/main/rust/src/runtime.rs
Labels: Ready For Review, enhancement

#111 Add i18n text for Peer ID in AddContact view
  src/i18n/es.json
  src/views/contacts/AddContact.js
Labels: Ready For Review, enhancement

#110 added external address to the javaScript
  android/app/src/main/java/io/locha/p2p/runtime/RuntimeEvents.java
  android/app/src/main/java/io/locha/p2p/service/ChatService.java
  android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
  android/app/src/main/java/io/locha/p2p/service/EventsDispatcher.java
  src/utils/chatService.js
Labels: Ready For Review

#117 Cleaning unused code
  .travis.yml
  __tests__/Actions/AplicationAction.js
  android/app/src/main/java/WiFiModule/WifiModule.java
  android/app/src/main/java/WiFiModule/WifiPackage.java
  android/app/src/main/java/com/lochameshchat/MainApplication.java
  android/app/src/main/java/upd/RNUdpServerModule.java
  android/app/src/main/java/upd/RNUdpServerPackage.java
  package.json
  src/WifiConnect.js
  src/index.js
  src/store/aplication/aplicationAction.js
  src/store/aplication/aplicationReducer.js
  src/store/contacts/contactsActions.js
  src/utils/chatService.js
  src/utils/notificationService.js
  src/utils/udp.js
  src/utils/utils.js
  src/views/home/Chat.js
  src/views/home/index.js
  yarn.lock
Labels: Ready For Review

#118 Update locha-p2p crate to latest version
  android/app/src/main/rust/Cargo.lock
  android/app/src/main/rust/Cargo.toml
  android/app/src/main/rust/src/runtime.rs
Labels: Ready For Review, enhancement

#120 add gh-actions workflow
  .github/workflows/nodejs.yml
Labels: Ready For Review

#119 Feature/add manual listen
  .github/workflows/nodejs.yml
  android/app/src/main/java/DeviceInfo/DeviceInfoModule.java
  android/app/src/main/java/DeviceInfo/Utils.java
  android/app/src/main/java/io/locha/p2p/runtime/Runtime.java
  android/app/src/main/java/io/locha/p2p/service/ChatService.java
  android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
  android/app/src/main/rust/src/runtime.rs
  src/components/Drawer.js
  src/i18n/en.json
  src/i18n/es.json
  src/store/aplication/aplicationAction.js
  src/store/aplication/aplicationReducer.js
  src/store/configuration/congurationAction.js
  src/store/configuration/congurationReducer.js
  src/store/constants.js
  src/utils/chatService.js
  src/views/config/AddManualAddress.js
  src/views/config/AddNewAddressListen.js
  src/views/config/AdministrativeComponent.js
  yarn.lock
Labels: Ready For Review

#122 added unit tests to missing components
  .gitignore
  App.js
  __Mocks__/index.js
  __tests__/Views/configuration/ AddNewAddressListen-test.js
  __tests__/Views/configuration/AddManualAddress-test.js
  __tests__/Views/configuration/AdministrativeComponent-test.js
  __tests__/Views/configuration/index.js
  __tests__/components/drawer-test.js
  src/components/Drawer.js
  src/database/index.js
  src/utils/chatService.js
  src/views/config/AddManualAddress.js
  src/views/config/AddNewAddressListen.js
  src/views/config/AdministrativeComponent.js
  src/views/config/ViewQR.js
Labels: Ready For Review

#125 removed websocket module
  android/app/src/main/java/RNWebSocket/RNWebsocketModule.java
  android/app/src/main/java/RNWebSocket/RNWebsocketPakage.java
  android/app/src/main/java/com/lochameshchat/MainApplication.java
Labels: Ready For Review
