Repository btcven/locha-mesh-chat, pull requests merged in 2020-01, with the labels that each got.

#16 iOS/local notification
  App.js
  ios/LocalNotification.m
  ios/LocalNotification.swift
  ios/LochaMeshChat-Bridging-Header.h
  ios/LochaMeshChat.xcodeproj/project.pbxproj
  ios/RNDeviceInfo.swift
  src/utils/notificationService.js
  src/views/home/index.js
Labels: enhancement

#22 Dev
  CONTRIBUTING.md
  README.md
  documents/configuration/files/Screenshot_20200109_173508_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200109_173543_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200109_173557_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200110_135047_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200110_135127_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200110_135149_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200110_135404_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200110_135621_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200110_140007_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200110_140312_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200110_140324_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200110_140334_com.lochameshchat.jpg
  documents/configuration/files/Screenshot_20200110_140347_com.lochameshchat.jpg
  package-lock.json
Labels: documentation

#23 README.md updates
  README.md
Labels: conflicts, documentation

#34 added view to add the name when we are creating an account this
  src/i18n/en.json
  src/i18n/es.json
  src/store/aplication/aplicationAction.js
  src/utils/socket.js
  src/views/LoadWallet/AddName.js
  src/views/LoadWallet/CreateAccount.js
Labels: enhancement

#35 added app version
  android/app/src/main/java/DeviceInfo/DeviceInfoModule.java
  android/app/src/main/java/DeviceInfo/DeviceInfoPackage.java
  android/app/src/main/java/com/lochameshchat/MainApplication.java
  ios/RNDeviceInfo.swift
  src/components/Drawer.js
  src/index.js
Labels: enhancement

#36 Restore pin
  package.json
  src/database/index.js
  src/database/schemas.js
  src/i18n/en.json
  src/i18n/es.json
  src/store/aplication/aplicationAction.js
  src/store/contacts/contactsActions.js
  src/views/LoadWallet/CreateAccount.js
  src/views/LoadWallet/Phrases.js
  src/views/LoadWallet/PinView.js
  src/views/LoadWallet/RestoreWithPin.js
  src/views/contacts/AddContact.js
  src/views/contacts/index.js
Labels: enhancement
