Repository btcven/locha-mesh-chat, pull requests merged in 2020-10, with the labels that each got.

#126 Feature/java unit test
  android/app/build.gradle
  android/app/src/androidTest/java/BitcoinJ/CryptoLibTest.java
  android/app/src/androidTest/java/DeviceInfo/UtilsTest.java
  android/app/src/androidTest/java/io/locha/p2p/runtime/RustNativeTest.java
  android/app/src/main/java/BitcoinJ/BitcoinModule.java
  android/app/src/main/java/BitcoinJ/CryptoLib.java
  android/app/src/main/java/BitcoinJ/EncryptorAES.java
  android/app/src/main/java/DeviceInfo/Utils.java
  android/app/src/main/java/LocalNotification/LocalNotificationModule.java
  android/app/src/main/java/io/locha/p2p/runtime/Runtime.java
  android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
  android/app/src/main/java/io/locha/p2p/service/EventsDispatcher.java
  android/app/src/test/java/BitcoinJ/BitcoinModuleTest.java
  android/app/src/test/java/DeviceInfo/UtilsTest.java
  android/build.gradle
Labels: Ready For Review

#127 Bye Travis
  .travis.yml
Labels: Area: CI/CD, Ready For Review

#129 fixes error when creating account
  android/app/src/main/java/BitcoinJ/CryptoLib.java
Labels: Ready For Review

#131 Build release APK with GH Actions
  .github/workflows/build_apk.yml
  android/gradle.properties.in
  android/keystore.sh
  package.json
Labels: Area: CI/CD, Ready For Review

#128 Update Rust locha-p2p crate
  android/app/src/main/java/io/locha/p2p/runtime/RuntimeEvents.java
  android/app/src/main/java/io/locha/p2p/service/EventsDispatcher.java
  android/app/src/main/rust/Cargo.lock
  android/app/src/main/rust/src/runtime.rs
  android/app/src/main/rust/src/util/jni_cache.rs
Labels: Ready For Review, enhancement

#132 Fix jni_cache module
  android/app/src/main/rust/src/util/jni_cache.rs
Labels: bug

#133 Bug/fix bugs found
  .gitignore
  __tests__/Views/chats/__snapshots__/home-test.js.snap
  __tests__/Views/chats/home-test.js
  android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
  package.json
  src/views/LoadWallet/CreateAccount.js
  src/views/LoadWallet/RestoreWithPin.js
  src/views/home/index.js
Labels: Ready For Review

#134 Pass bootstrap nodes to RuntimeConfig
  android/app/src/main/rust/src/runtime.rs
Labels: Ready For Review, bug

#135 activate or desactivate upnp completed
  __Mocks__/index.js
  __tests__/Views/configuration/AdministrativeComponent-test.js
  src/i18n/en.json
  src/i18n/es.json
  src/store/aplication/aplicationAction.js
  src/utils/chatService.js
  src/views/config/AdministrativeComponent.js
  src/views/home/index.js
Labels: Ready For Review

#138 updated locha-p2p
  android/app/src/main/rust/Cargo.lock
Labels: Ready For Review

#141 Feature/error handler
  __Mocks__/index.js
  android/app/src/main/java/DeviceInfo/DeviceInfoModule.java
  android/app/src/main/java/DeviceInfo/Utils.java
  android/app/src/main/java/com/lochameshchat/MainApplication.java
  android/app/src/test/java/DeviceInfo/UtilsTest.java
  android/settings.gradle
  ios/LochaMeshChat.xcodeproj/project.pbxproj
  package.json
  src/components/Drawer.js
  src/index.js
  src/utils/ErrorHandler.js
  yarn.lock
Labels: Status: Ready For Review

#142 Feature/automatic version
  .github/workflows/build_apk.yml
  android/app/build.gradle
  android/keystore.sh
Labels: Status: Ready For Review

#143 Feature/broadcast chat
  __tests__/Actions/AplicationAction.js
  __tests__/Views/chats/__snapshots__/home-test.js.snap
  __tests__/Views/chats/home-test.js
  __tests__/Views/configuration/AdministrativeComponent-test.js
  src/components/Header.js
  src/i18n/en.json
  src/i18n/es.json
  src/store/aplication/aplicationAction.js
  src/store/chats/chatAction.js
  src/store/chats/chatReducers.js
  src/store/constants.js
  src/utils/chatService.js
  src/utils/constans.js
  src/utils/utils.js
  src/views/config/AdministrativeComponent.js
  src/views/home/Chat.js
  src/views/home/ChatForm.js
  src/views/home/Messages.js
  src/views/home/index.js
Labels: Status: Ready For Review

#144 Pass originator PeerId on onNewMessage event
  android/app/src/main/java/io/locha/p2p/runtime/RuntimeEvents.java
  android/app/src/main/java/io/locha/p2p/service/EventsDispatcher.java
  android/app/src/main/rust/Cargo.lock
  android/app/src/main/rust/Cargo.toml
  android/app/src/main/rust/src/runtime.rs
  android/app/src/main/rust/src/util/jni_cache.rs
Labels: Status: Ready For Review, Type: Enhancement

#145 removed the fromUID of messages that go through rust
  __Mocks__/dataMock.js
  __Mocks__/index.js
  __tests__/Views/chats/chatForm-test.js
  __tests__/Views/chats/home-test.js
  __tests__/Views/chats/message-test.js
  __tests__/Views/configuration/ AddNewAddressListen-test.js
  __tests__/Views/configuration/AddManualAddress-test.js
  __tests__/Views/configuration/ViewQR-test.js
  android/app/src/main/java/DeviceInfo/Utils.java
  android/app/src/main/java/io/locha/p2p/service/EventsDispatcher.java
  src/database/index.js
  src/database/realmDatabase.js
  src/index.js
  src/store/aplication/aplicationAction.js
  src/store/chats/chatAction.js
  src/store/chats/chatReducers.js
  src/utils/ErrorHandler.js
  src/utils/utils.js
  src/views/config/AddManualAddress.js
  src/views/config/AdministrativeComponent.js
  src/views/config/ViewQR.js
  src/views/config/index.js
  src/views/home/Chat.js
  src/views/home/ChatForm.js
Labels: Status: Ready For Review
