Repository btcven/locha-mesh-chat, pull requests merged in 2020-08, with the labels that each got.

#83 Remove repeated entry on AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
Labels: Ready For Review, enhancement

#82 Feature/add crypto libs
  __Mocks__/index.js
  __tests__/Views/LoadWallet/CreateAccount-test.js
  __tests__/Views/LoadWallet/addName-test.js
  __tests__/Views/LoadWallet/phrases-test.js
  __tests__/Views/configuration/index.js
  __tests__/Views/contacts/addContact-test.js
  __tests__/bitcoin-test.js
  __tests__/realm-test.js
  __tests__/utils-test.js
  android/app/build.gradle
  android/app/src/main/java/BitcoinJ/BitcoinModule.java
  android/app/src/main/java/BitcoinJ/EncryptorAES.java
  android/app/src/main/java/DeviceInfo/DeviceInfoPackage.java
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  languages.js
  mockDatabase/default.realm
  mockDatabase/default.realm.lock
  mockDatabase/default.realm.management/access_control.control.mx
  mockDatabase/default.realm.management/access_control.write.mx
  mockDatabase/seed.realm
  mockDatabase/seed.realm.lock
  mockDatabase/seed.realm.management/access_control.control.mx
  mockDatabase/seed.realm.management/access_control.write.mx
  package.json
  src/components/Header.js
  src/database/index.js
  src/database/realmDatabase.js
  src/i18n/index.js
  src/index.js
  src/store/aplication/aplicationAction.js
  src/store/chats/chatReducers.js
  src/store/configuration/congurationAction.js
  src/store/constants.js
  src/store/deviceSettins/deviceSettingsAction.js
  src/utils/Bitcoin.js
  src/utils/udp.js
  src/utils/utils.js
  src/views/LoadWallet/CreateAccount.js
  src/views/LoadWallet/index.js
  src/views/config/index.js
  src/views/contacts/AddContact.js
  src/views/deviceSettings/index.js
  src/views/deviceSettings/settingsPanel.js
  src/views/home/Chat.js
  src/views/home/ChatForm.js
  src/views/home/Messages.js
  yarn.lock
Labels: Ready For Review

#84 Add i18n entries for WifiConnect
  src/WifiConnect.js
  src/i18n/en.json
  src/i18n/es.json
Labels: Ready For Review, enhancement

#88 Fix CI process
  .travis.yml
  package-lock.json
Labels: Area: CI/CD, Ready For Review

#92 Cherry pick #90 and #91 PRs into only one
  .gitignore
  App.js
  __Mocks__/index.js
  android/app/src/main/java/DeviceInfo/Utils.java
  android/app/src/main/java/io/locha/p2p/LochaP2PPackage.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatService.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatServiceEvents.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatServiceModule.java
  android/app/src/main/rust/Cargo.lock
  android/app/src/main/rust/Cargo.toml
  android/app/src/main/rust/examples/node.rs
  android/app/src/main/rust/src/runtime.rs
  android/app/src/main/rust/src/runtime/chat_service.rs
  android/app/src/main/rust/src/runtime/chat_service/config.rs
  android/app/src/main/rust/src/runtime/chat_service/error.rs
  android/app/src/main/rust/src/runtime/chat_service/events.rs
  android/app/src/main/rust/src/runtime/chat_service/sync_start_cond.rs
  package.json
  src/database/realmDatabase.js
  src/database/schemas.js
  src/store/aplication/aplicationAction.js
  src/store/chats/chatAction.js
  src/store/configuration/congurationReducer.js
  src/utils/chatService.js
  src/utils/udp.js
  src/utils/utils.js
  src/views/LoadWallet/CreateAccount.js
  src/views/config/ViewQR.js
  src/views/config/index.js
  src/views/home/Chat.js
  src/views/home/ChatBody.js
  src/views/home/ChatForm.js
  src/views/home/index.js
Labels: Ready For Review

#95 Use btcven/locha-p2p as a dependency.
  android/app/build.gradle
  android/app/src/main/rust/Cargo.lock
  android/app/src/main/rust/Cargo.toml
  android/app/src/main/rust/examples/node.rs
  android/app/src/main/rust/src/runtime.rs
  android/app/src/main/rust/src/runtime/chat_service.rs
  android/app/src/main/rust/src/runtime/chat_service/config.rs
  android/app/src/main/rust/src/runtime/chat_service/error.rs
  android/app/src/main/rust/src/runtime/chat_service/events.rs
  android/app/src/main/rust/src/runtime/chat_service/sync_start_cond.rs
Labels: Ready For Review

#86 Use AsyncStorage from @react-native-community/async-storage
  android/app/src/main/java/io/locha/p2p/util/LibraryLoader.java
  package.json
  src/i18n/index.js
  src/store/aplication/aplicationAction.js
  src/store/deviceSettins/deviceSettingsAction.js
  src/views/config/Language.js
  yarn.lock
Labels: Ready For Review, dependencies

#96 Refactor/chat structure v2
  __Mocks__/index.js
  __tests__/Views/configuration/ViewQR-test.js
  __tests__/Views/configuration/index.js
  android/app/src/main/java/LocalNotification/LocalNotificationModule.java
  android/app/src/main/java/io/locha/p2p/runtime/ChatServiceModule.java
  android/app/src/main/rust/src/runtime.rs
  src/database/index.js
  src/database/realmDatabase.js
  src/database/schemas.js
  src/i18n/en.json
  src/i18n/es.json
  src/store/aplication/aplicationAction.js
  src/store/aplication/aplicationReducer.js
  src/store/chats/chatAction.js
  src/store/configuration/congurationReducer.js
  src/store/constants.js
  src/utils/chatService.js
  src/utils/notificationService.js
  src/utils/utils.js
  src/views/LoadWallet/index.js
  src/views/config/ViewQR.js
  src/views/config/index.js
  src/views/contacts/AddContact.js
  src/views/home/Chat.js
Labels: work in progress
